<a href="https://colab.research.google.com/github/EmiiFernandez/actividades_data_sciente_ypf/blob/main/notebook/C03_Notebook-05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🤖 Guía de Asistencia con IA: IA como Copiloto de Programación

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Explicación de código**: Si encuentras una función o línea que no comprendes, pregúntale a la IA: *'Explica qué hace esta función línea por línea en Python: [pega tu código]'*.
- **Corrección de errores**: Si tienes un error al ejecutar, copia el error completo y pregúntale: *'¿Por qué este código genera este error y cómo lo soluciono? [pega tu código y error]'*.
- **Optimización**: Pregunta: *'¿Cómo puedo escribir este código de forma más eficiente y limpia?'*.


# Programa Ingenias+ Data Science

In [53]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


It seems that Google Drive could not be mounted. Please run the cell below and ensure you authorize the connection in the pop-up window.

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [73]:
expvida = pd.read_csv('/content/drive/MyDrive/Data Science - EnergIA/life_expectancy_data.csv')

Now that Google Drive should be mounted, you can verify your file path. For demonstration purposes, I will load a sample CSV file available in Colab to define `expvida`. You will need to update the path to your `life_expectancy_data.csv` once you confirm its correct location in your Drive.

In [56]:
#Importar numpy
import numpy as np

In [57]:
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [58]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
Ejercicio1=np.zeros(12)
print(Ejercicio1)
len (Ejercicio1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [59]:
#prueba: arreglo de unos de longitud 5
prueba=np.ones(5)
print(prueba)

[1. 1. 1. 1. 1.]


In [60]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
Ejercicio2=np.zeros(10)
Ejercicio2[4]=10
print(Ejercicio2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [61]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
prueba[3]=7
print(prueba)

[1. 1. 1. 7. 1.]


In [62]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [63]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
Ejercicio4=np.arange(9).reshape(3,3)
print(Ejercicio4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [64]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y
Ejercicio5=np.random.rand(100)
print(Ejercicio5)
print("")
media = np.mean(Ejercicio5)
print("Media:", media)
print("")
varianza = np.var(Ejercicio5)
print("Varianza:", varianza)

[0.61382226 0.51263904 0.12548769 0.41074491 0.22766742 0.87668151
 0.75016294 0.15377969 0.75270598 0.51327063 0.75119738 0.41115781
 0.1165292  0.77110518 0.01368817 0.87515581 0.33315696 0.18619445
 0.03969867 0.03253855 0.96086958 0.1807605  0.56599814 0.66955058
 0.83311683 0.29866778 0.48134401 0.48801364 0.73867902 0.58080421
 0.63928426 0.59255994 0.23137238 0.0705864  0.87154424 0.82973611
 0.33727814 0.9492617  0.37759141 0.30208967 0.07427187 0.60616027
 0.5538225  0.19178885 0.7755014  0.06734388 0.94591293 0.14891666
 0.92319093 0.72796054 0.21481752 0.93718863 0.32871703 0.07583489
 0.47630251 0.2560267  0.87167162 0.8916326  0.09326224 0.72119927
 0.76365033 0.09262599 0.58372056 0.97115262 0.29797429 0.35824254
 0.95868804 0.53636656 0.61800885 0.55685501 0.69861119 0.43506272
 0.02444834 0.53872707 0.19107504 0.69526638 0.01248277 0.78548384
 0.04735434 0.11931002 0.77600094 0.4774338  0.23325791 0.72388177
 0.70401725 0.95510849 0.45195045 0.43678469 0.96247616 0.8888

In [65]:
#pruba 5: crear arreglo de 25 numeros aleatorios y calcular media y varianza
Prueba5=np.random.rand(25)
print(Prueba5)
print("")
media25=np.mean(Prueba5)
print("Media:", media25 )
print("")
varianza25=np.var(Prueba5)
print("Varianza:", varianza25)

[0.64675617 0.29426566 0.5585143  0.9502022  0.52883085 0.29238575
 0.46990696 0.17190087 0.38566163 0.38110473 0.63689254 0.28414817
 0.44563448 0.54319883 0.07250539 0.46977733 0.48345092 0.15588995
 0.17498037 0.78864442 0.82031158 0.69128108 0.794818   0.60875101
 0.31436288]

Media: 0.47856704397167005

Varianza: 0.05088141603880017


In [66]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
Ejercicio6 = np.sum(Ejercicio5)/[len(Ejercicio5)]
print(Ejercicio6)

[0.51212683]


In [67]:
#prueba6: Calcular la media de un arreglo usando np.sum
prueba6=np.sum(Prueba5)/[len(Prueba5)]
print(prueba6)
prueba6a=np.mean(Prueba5)
print(prueba6a)

[0.47856704]
0.47856704397167005


In [68]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
Ejercicio7=np.sum((Ejercicio5-np.mean(Ejercicio5))**2)/[len(Ejercicio5)]
print(Ejercicio7)

[0.08951301]


### Visualización de datos del CSV

In [74]:
print("Las primeras 5 filas del DataFrame 'expvida':")
display(expvida.head())

Las primeras 5 filas del DataFrame 'expvida':


,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5


In [75]:
print("\nInformación general del DataFrame 'expvida' (tipos de datos y valores no nulos):")
expvida.info()


Información general del DataFrame 'expvida' (tipos de datos y valores no nulos):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Country                          2938 non-null   object 
 1   Year                             2938 non-null   int64  
 2   Status                           2938 non-null   object 
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64  
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64  
 10   BMI                             2904 non-null   float64
 11  

In [76]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn

Ejercicio8=np.random.rand(15) #en mi caso elegi 15 numeros random
print(Ejercicio8)

[0.67017609 0.58971284 0.34954493 0.4124873  0.9545186  0.72181924
 0.01402457 0.47927552 0.75628501 0.96600254 0.79839261 0.22227488
 0.64474973 0.37283228 0.20006229]
