<a href="https://colab.research.google.com/github/EmiiFernandez/actividades_data_sciente_ypf/blob/main/notebook/C3_Notebook-5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🤖 Guía de Asistencia con IA: IA como Copiloto de Programación

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Explicación de código**: Si encuentras una función o línea que no comprendes, pregúntale a la IA: *'Explica qué hace esta función línea por línea en Python: [pega tu código]'*.
- **Corrección de errores**: Si tienes un error al ejecutar, copia el error completo y pregúntale: *'¿Por qué este código genera este error y cómo lo soluciono? [pega tu código y error]'*.
- **Optimización**: Pregunta: *'¿Cómo puedo escribir este código de forma más eficiente y limpia?'*.


# Programa Ingenias+ Data Science

In [43]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


It seems that Google Drive could not be mounted. Please run the cell below and ensure you authorize the connection in the pop-up window.

In [45]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Now that Google Drive should be mounted, you can verify your file path. For demonstration purposes, I will load a sample CSV file available in Colab to define `expvida`. You will need to update the path to your `life_expectancy_data.csv` once you confirm its correct location in your Drive.

In [27]:
csv_file_path = '/content/drive/MyDrive/Data Science - EnergIA - YPF/life_expectancy_data.csv' # ¡ACTUALIZA ESTA RUTA CON LA TUYA!
try:
    expvida = pd.read_csv(csv_file_path)
    print(f"Archivo '{csv_file_path}' cargado exitosamente.")
except FileNotFoundError:
    print(f"Error: El archivo '{csv_file_path}' no se encontró. Por favor, verifica la ruta.")
except Exception as e:
    print(f"Ocurrió un error al cargar el archivo: {e}")

Error: El archivo '/content/drive/MyDrive/life_expectancy_data.csv' no se encontró. Por favor, verifica la ruta.


In [28]:
#Importar numpy
import numpy as np

In [29]:
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [30]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
Ejercicio1=np.zeros(12)
print(Ejercicio1)
len (Ejercicio1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [31]:
#prueba: arreglo de unos de longitud 5
prueba=np.ones(5)
print(prueba)

[1. 1. 1. 1. 1.]


In [32]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
Ejercicio2=np.zeros(10)
Ejercicio2[4]=10
print(Ejercicio2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [33]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
prueba[3]=7
print(prueba)

[1. 1. 1. 7. 1.]


In [34]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [35]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
Ejercicio4=np.arange(9).reshape(3,3)
print(Ejercicio4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
Ejercicio5=np.random.rand(100)
print(Ejercicio5)
print("")
media = np.mean(Ejercicio5)
print("Media:", media)
print("")
varianza = np.var(Ejercicio5)
print("Varianza:", varianza)

[0.37627572 0.9768225  0.2503258  0.15081101 0.60780536 0.2332858
 0.10077209 0.60145539 0.4028018  0.84784914 0.34504288 0.10402872
 0.12402597 0.323832   0.94952224 0.2603006  0.90053278 0.54899376
 0.53359671 0.99489675 0.59461395 0.98295307 0.90066949 0.69134471
 0.84185557 0.9101208  0.0201775  0.89078968 0.45101551 0.86084037
 0.01388465 0.99342841 0.93689837 0.87012584 0.78703882 0.2653868
 0.40253358 0.3171446  0.74776583 0.61008094 0.3658739  0.19493514
 0.71029874 0.78851323 0.46190271 0.679474   0.28171616 0.40921845
 0.1339667  0.18680042 0.19463364 0.78285377 0.04381785 0.91983998
 0.54319132 0.32607551 0.77419817 0.56143362 0.13981973 0.1363758
 0.08269731 0.42244068 0.25492972 0.24581543 0.21236715 0.1872743
 0.99200704 0.66304953 0.57343496 0.25749383 0.01477906 0.26639199
 0.20960361 0.02301757 0.42413907 0.08605387 0.57602676 0.90918979
 0.24541689 0.6072557  0.78349941 0.01906742 0.03371831 0.2563584
 0.46364112 0.97099645 0.26911064 0.41062293 0.3298109  0.96838534


In [37]:
#pruba 5: crear arreglo de 25 numeros aleatorios y calcular media y varianza
Prueba5=np.random.rand(25)
print(Prueba5)
print("")
media25=np.mean(Prueba5)
print("Media:", media25 )
print("")
varianza25=np.var(Prueba5)
print("Varianza:", varianza25)

[0.48252177 0.86093057 0.27267573 0.60912643 0.18351249 0.3302182
 0.028855   0.70374416 0.75186647 0.20473335 0.04748777 0.62541721
 0.58125851 0.03262315 0.42185773 0.34529609 0.17168256 0.55568567
 0.32668614 0.18069877 0.12647712 0.98787613 0.85568176 0.78404164
 0.38244135]

Media: 0.43413583166426756

Varianza: 0.07783295567287954


In [38]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
Ejercicio6 = np.sum(Ejercicio5)/[len(Ejercicio5)]
print(Ejercicio6)

[0.47689014]


In [39]:
#prueba6: Calcular la media de un arreglo usando np.sum
prueba6=np.sum(Prueba5)/[len(Prueba5)]
print(prueba6)
prueba6a=np.mean(Prueba5)
print(prueba6a)

[0.43413583]
0.43413583166426756


In [40]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
Ejercicio7=np.sum((Ejercicio5-np.mean(Ejercicio5))**2)/[len(Ejercicio5)]
print(Ejercicio7)

[0.09253323]


### Visualización de datos del CSV

In [41]:
print("Las primeras 5 filas del DataFrame 'expvida':")
display(expvida.head())

Las primeras 5 filas del DataFrame 'expvida':


NameError: name 'expvida' is not defined

In [ ]:
print("\nInformación general del DataFrame 'expvida' (tipos de datos y valores no nulos):")
expvida.info()

In [ ]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn

Ejercicio8=np.random.rand(15) #en mi caso elegi 15 numeros random
print(Ejercicio8)