<a href="https://colab.research.google.com/github/EmiiFernandez/actividades_data_sciente_ypf/blob/main/C3_Notebook-5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🤖 Guía de Asistencia con IA: IA como Copiloto de Programación

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Explicación de código**: Si encuentras una función o línea que no comprendes, pregúntale a la IA: *'Explica qué hace esta función línea por línea en Python: [pega tu código]'*.
- **Corrección de errores**: Si tienes un error al ejecutar, copia el error completo y pregúntale: *'¿Por qué este código genera este error y cómo lo soluciono? [pega tu código y error]'*.
- **Optimización**: Pregunta: *'¿Cómo puedo escribir este código de forma más eficiente y limpia?'*.


# Programa Ingenias+ Data Science

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

It seems that Google Drive could not be mounted. Please run the cell below and ensure you authorize the connection in the pop-up window.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Now that Google Drive should be mounted, you can verify your file path. For demonstration purposes, I will load a sample CSV file available in Colab to define `expvida`. You will need to update the path to your `life_expectancy_data.csv` once you confirm its correct location in your Drive.

In [ ]:
#Importar numpy
import numpy as np

In [ ]:
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [ ]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
Ejercicio1=np.zeros(12)
print(Ejercicio1)
len (Ejercicio1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [ ]:
#prueba: arreglo de unos de longitud 5
prueba=np.ones(5)
print(prueba)

[1. 1. 1. 1. 1.]


In [ ]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
Ejercicio2=np.zeros(10)
Ejercicio2[4]=10
print(Ejercicio2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
prueba[3]=7
print(prueba)

[1. 1. 1. 7. 1.]


In [ ]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
Ejercicio4=np.arange(9).reshape(3,3)
print(Ejercicio4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
Ejercicio5=np.random.rand(100)
print(Ejercicio5)
print("")
media = np.mean(Ejercicio5)
print("Media:", media)
print("")
varianza = np.var(Ejercicio5)
print("Varianza:", varianza)

[0.72836018 0.31652472 0.78061721 0.99472104 0.22430268 0.90365961
 0.06885193 0.91896776 0.50197878 0.45518174 0.13877837 0.85611392
 0.30313391 0.41527943 0.1564402  0.33922201 0.57755687 0.50503013
 0.32544032 0.44629199 0.96309187 0.69630172 0.67526222 0.20328301
 0.04445587 0.85055142 0.81982352 0.43422626 0.10986511 0.89527572
 0.44058664 0.24342242 0.65946144 0.18296815 0.50582002 0.92176717
 0.59291936 0.65830812 0.23821837 0.22762579 0.69881837 0.775277
 0.09770399 0.25215752 0.52767756 0.26335017 0.68194113 0.06952017
 0.68857685 0.81034575 0.94268663 0.25472784 0.60170661 0.0715701
 0.43880054 0.60172358 0.91398975 0.94506229 0.88954611 0.75831246
 0.91192338 0.29118667 0.90370821 0.84347976 0.53546834 0.60796518
 0.57413786 0.60018231 0.58825827 0.67356422 0.73735294 0.5810621
 0.24269075 0.76813569 0.0881919  0.37144353 0.92992781 0.6067213
 0.95327899 0.27894583 0.67226968 0.08632705 0.54730902 0.76221732
 0.1492966  0.38951411 0.28667314 0.9827624  0.73619368 0.77055055


In [ ]:
#pruba 5: crear arreglo de 25 numeros aleatorios y calcular media y varianza
Prueba5=np.random.rand(25)
print(Prueba5)
print("")
media25=np.mean(Prueba5)
print("Media:", media25 )
print("")
varianza25=np.var(Prueba5)
print("Varianza:", varianza25)

[0.04411518 0.25010949 0.50184918 0.49903769 0.53069333 0.71589916
 0.32664109 0.13330933 0.53423817 0.76694188 0.02976775 0.72318794
 0.18346215 0.1411797  0.68058433 0.37928806 0.18012319 0.89270772
 0.94031889 0.82629536 0.24705584 0.86321559 0.88862517 0.6243893
 0.38677698]

Media: 0.4915924993075833

Varianza: 0.08128771770509192


In [ ]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
Ejercicio6 = np.sum(Ejercicio5)/[len(Ejercicio5)]
print(Ejercicio6)

[0.53339901]


In [ ]:
#prueba6: Calcular la media de un arreglo usando np.sum
prueba6=np.sum(Prueba5)/[len(Prueba5)]
print(prueba6)
prueba6a=np.mean(Prueba5)
print(prueba6a)

[0.4915925]
0.4915924993075833


In [ ]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
Ejercicio7=np.sum((Ejercicio5-np.mean(Ejercicio5))**2)/[len(Ejercicio5)]
print(Ejercicio7)

[0.07936795]


### Visualización de datos del CSV

In [ ]:
print("Las primeras 5 filas del DataFrame 'expvida':")
display(expvida.head())

Las primeras 5 filas del DataFrame 'expvida':


NameError: name 'expvida' is not defined

In [ ]:
print("\nInformación general del DataFrame 'expvida' (tipos de datos y valores no nulos):")
expvida.info()

In [ ]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn

Ejercicio8=np.random.rand(15) #en mi caso elegi 15 numeros random
print(Ejercicio8)

[0.21043671 0.48271954 0.51688911 0.91270162 0.83075664 0.28607877
 0.85988108 0.20433493 0.36545964 0.55077292 0.08412542 0.91719666
 0.97240791 0.05753317 0.79009228]
